"""
Document generation router.
Produces .docx inspection reports, .py engineering scripts,
.pptx presentations, .xlsx spreadsheets.
All content generated by local Ollama — no cloud calls.
"""
import asyncio
import json
import os
import re
import uuid
from pathlib import Path
from typing import Optional

import httpx
from docx import Document
from docx.shared import Pt, RGBColor, Inches
from docx.enum.text import WD_ALIGN_PARAGRAPH
from fastapi import APIRouter, HTTPException
from pydantic import BaseModel

from config import MODELS, OLLAMA_BASE_URL, route_model
from routers.network_monitor import record_call

router = APIRouter()
OUTPUT_DIR = Path("outputs")
OUTPUT_DIR.mkdir(exist_ok=True)


class DocRequest(BaseModel):
    prompt: str
    doc_type: str = "report"  # report | script | sop | pptx | xlsx
    title: Optional[str] = None
    equipment_id: Optional[str] = None


async def ollama_generate(prompt: str, model_tag: str) -> str:
    record_call("ollama_local", prompt[:60])
    payload = {
        "model": model_tag,
        "prompt": prompt,
        "stream": False,
        "options": {"num_ctx": 4096, "temperature": 0.6, "num_predict": 1024},
    }
    async with httpx.AsyncClient(timeout=180) as client:
        r = await client.post(f"{OLLAMA_BASE_URL}/api/generate", json=payload)
        return r.json().get("response", "")


def build_inspection_report(title: str, content: str, equipment_id: str) -> Path:
    """Generate a formatted .docx inspection report."""
    doc = Document()

    # Header
    header = doc.sections[0].header
    header_para = header.paragraphs[0]
    header_para.text = "MANGALORE REFINERY AND PETROCHEMICALS LIMITED"
    header_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = header_para.runs[0]
    run.bold = True
    run.font.size = Pt(10)
    run.font.color.rgb = RGBColor(0x1a, 0x1a, 0x2e)

    # Title
    title_para = doc.add_heading(title, level=1)
    title_para.alignment = WD_ALIGN_PARAGRAPH.CENTER

    # Metadata table
    table = doc.add_table(rows=4, cols=2)
    table.style = "Light Grid Accent 1"
    cells = [
        ("Equipment ID", equipment_id),
        ("Inspection Date", "05-Sep-2026"),
        ("Inspector", "Automated — MRPL AI Workbench"),
        ("Classification", "INTERNAL / CONFIDENTIAL"),
    ]
    for i, (key, val) in enumerate(cells):
        table.rows[i].cells[0].text = key
        table.rows[i].cells[1].text = val

    doc.add_paragraph()

    # Content — split on \n\n for sections
    for para in content.strip().split("\n\n"):
        para = para.strip()
        if para.startswith("##"):
            doc.add_heading(para.lstrip("#").strip(), level=2)
        elif para.startswith("#"):
            doc.add_heading(para.lstrip("#").strip(), level=1)
        elif para:
            doc.add_paragraph(para)

    # Footer note
    doc.add_paragraph()
    note = doc.add_paragraph(
        "⚠ This document was generated by the MRPL AI Workbench. "
        "All inference ran on-premises via Ollama. No data left the facility."
    )
    note.runs[0].italic = True
    note.runs[0].font.size = Pt(8)

    filename = f"report_{uuid.uuid4().hex[:8]}.docx"
    path = OUTPUT_DIR / filename
    doc.save(str(path))
    return path


def build_python_script(title: str, content: str) -> Path:
    """Save generated Python script."""
    # Strip markdown code fences
    lines = content.strip().splitlines()
    if lines and lines[0].startswith("```"):
        lines = lines[1:]
    if lines and lines[-1].startswith("```"):
        lines = lines[:-1]

    header = f'''"""
{title}
Generated by MRPL AI Workbench — Qwen2.5-Coder 3B
All computation is local. No external API calls.
Date: 05-Sep-2026
"""
'''
    script = header + "\n".join(lines)
    filename = f"script_{uuid.uuid4().hex[:8]}.py"
    path = OUTPUT_DIR / filename
    path.write_text(script, encoding="utf-8")
    return path


def build_pptx(title: str, content: str) -> Path:
    """Generate a .pptx presentation from LLM content."""
    from pptx import Presentation
    from pptx.util import Inches as PptxInches, Pt as PptxPt
    from pptx.dml.color import RGBColor as PptxRGB
    from pptx.enum.text import PP_ALIGN

    prs = Presentation()
    prs.slide_width = PptxInches(13.333)
    prs.slide_height = PptxInches(7.5)

    # --- Title Slide ---
    slide = prs.slides.add_slide(prs.slide_layouts[6])  # blank
    bg = slide.background.fill
    bg.solid()
    bg.fore_color.rgb = PptxRGB(0x0D, 0x1B, 0x2A)

    txBox = slide.shapes.add_textbox(PptxInches(1), PptxInches(2), PptxInches(11), PptxInches(2))
    tf = txBox.text_frame
    p = tf.paragraphs[0]
    p.text = title
    p.font.size = PptxPt(36)
    p.font.bold = True
    p.font.color.rgb = PptxRGB(0xA7, 0xC8, 0xFF)
    p.alignment = PP_ALIGN.CENTER

    p2 = tf.add_paragraph()
    p2.text = "MRPL AI Workbench — Generated On-Premises"
    p2.font.size = PptxPt(16)
    p2.font.color.rgb = PptxRGB(0xC3, 0xC6, 0xD1)
    p2.alignment = PP_ALIGN.CENTER

    p3 = tf.add_paragraph()
    p3.text = "CONFIDENTIAL — Zero External API Calls"
    p3.font.size = PptxPt(12)
    p3.font.color.rgb = PptxRGB(0x38, 0xDE, 0xBB)
    p3.alignment = PP_ALIGN.CENTER

    # --- Content Slides ---
    sections = re.split(r'\n##\s+', content)
    for section in sections:
        section = section.strip()
        if not section:
            continue

        lines = section.split("\n", 1)
        heading = lines[0].lstrip("#").strip()
        body = lines[1].strip() if len(lines) > 1 else ""

        slide = prs.slides.add_slide(prs.slide_layouts[6])
        bg = slide.background.fill
        bg.solid()
        bg.fore_color.rgb = PptxRGB(0x0D, 0x1B, 0x2A)

        # Heading
        txBox = slide.shapes.add_textbox(PptxInches(0.8), PptxInches(0.5), PptxInches(11.5), PptxInches(1))
        tf = txBox.text_frame
        p = tf.paragraphs[0]
        p.text = heading
        p.font.size = PptxPt(28)
        p.font.bold = True
        p.font.color.rgb = PptxRGB(0xA7, 0xC8, 0xFF)

        # Body
        if body:
            txBox2 = slide.shapes.add_textbox(PptxInches(0.8), PptxInches(1.8), PptxInches(11.5), PptxInches(5))
            tf2 = txBox2.text_frame
            tf2.word_wrap = True
            for i, bullet in enumerate(body.split("\n")):
                bullet = bullet.strip().lstrip("-•* ")
                if not bullet:
                    continue
                p = tf2.paragraphs[0] if i == 0 else tf2.add_paragraph()
                p.text = f"▸ {bullet}"
                p.font.size = PptxPt(16)
                p.font.color.rgb = PptxRGB(0xD6, 0xE3, 0xFF)
                p.space_after = PptxPt(8)

    filename = f"presentation_{uuid.uuid4().hex[:8]}.pptx"
    path = OUTPUT_DIR / filename
    prs.save(str(path))
    return path


def build_xlsx(title: str, content: str) -> Path:
    """Generate a .xlsx spreadsheet from LLM content."""
    from openpyxl import Workbook
    from openpyxl.styles import Font, PatternFill, Alignment, Border, Side

    wb = Workbook()
    ws = wb.active
    ws.title = "Data"

    # Styles
    header_font = Font(name="Calibri", size=12, bold=True, color="FFFFFF")
    header_fill = PatternFill(start_color="0D1B2A", end_color="0D1B2A", fill_type="solid")
    data_font = Font(name="Calibri", size=11)
    border = Border(
        left=Side(style="thin"), right=Side(style="thin"),
        top=Side(style="thin"), bottom=Side(style="thin"),
    )

    # Title row
    ws.merge_cells("A1:F1")
    ws["A1"] = title
    ws["A1"].font = Font(name="Calibri", size=14, bold=True, color="3A5F94")

    ws.merge_cells("A2:F2")
    ws["A2"] = "Generated by MRPL AI Workbench — On-Premises Only"
    ws["A2"].font = Font(name="Calibri", size=9, italic=True, color="888888")

    # Parse content into rows
    lines = [l.strip() for l in content.strip().split("\n") if l.strip()]
    row_idx = 4

    for line in lines:
        # Try to split by | (table format) or , or tabs
        if "|" in line:
            cells = [c.strip() for c in line.split("|") if c.strip()]
        elif "\t" in line:
            cells = [c.strip() for c in line.split("\t")]
        elif "," in line and line.count(",") >= 2:
            cells = [c.strip() for c in line.split(",")]
        else:
            cells = [line]

        for col_idx, val in enumerate(cells, 1):
            cell = ws.cell(row=row_idx, column=col_idx, value=val)
            cell.font = data_font
            cell.border = border
            cell.alignment = Alignment(wrap_text=True)

            # Style header rows
            if row_idx == 4:
                cell.font = header_font
                cell.fill = header_fill

        row_idx += 1

    # Auto-width columns
    for col in ws.columns:
        max_len = max((len(str(cell.value or "")) for cell in col), default=10)
        ws.column_dimensions[col[0].column_letter].width = min(max_len + 4, 40)

    filename = f"spreadsheet_{uuid.uuid4().hex[:8]}.xlsx"
    path = OUTPUT_DIR / filename
    wb.save(str(path))
    return path


@router.post("/generate")
async def generate_document(req: DocRequest):
    model_key = route_model(req.prompt, None)
    model_tag = MODELS[model_key]["tag"]
    title = req.title or "MRPL Technical Document"
    eq_id = req.equipment_id or "EQ-UNKNOWN"

    if req.doc_type == "report":
        full_prompt = (
            f"You are a technical writer for Mangalore Refinery and Petrochemicals Limited (MRPL). "
            f"Write a detailed inspection report for the following:\n\n{req.prompt}\n\n"
            f"Use sections: Executive Summary, Findings, Risk Assessment, Recommendations, Conclusion. "
            f"Use ## for section headers. Be specific and technical."
        )
        content = await ollama_generate(full_prompt, model_tag)
        file_path = build_inspection_report(title, content, eq_id)
        return {
            "status": "success",
            "file": file_path.name,
            "download_url": f"/outputs/{file_path.name}",
            "model_used": MODELS[model_key]["display"],
            "doc_type": "docx",
            "external_calls": 0,
        }

    elif req.doc_type == "script":
        full_prompt = (
            f"You are a Python engineer at MRPL. "
            f"Write a complete, runnable Python script for:\n\n{req.prompt}\n\n"
            f"Include imports, docstrings, type hints, and example usage in __main__. "
            f"Return only the Python code."
        )
        content = await ollama_generate(full_prompt, model_tag)
        file_path = build_python_script(title, content)
        return {
            "status": "success",
            "file": file_path.name,
            "download_url": f"/outputs/{file_path.name}",
            "model_used": MODELS[model_key]["display"],
            "doc_type": "py",
            "content_preview": content[:500],
            "external_calls": 0,
        }

    elif req.doc_type == "sop":
        full_prompt = (
            f"Write a Standard Operating Procedure (SOP) for MRPL regarding:\n\n{req.prompt}\n\n"
            f"Format: Purpose, Scope, Responsibilities, Step-by-step Procedure, Safety Precautions, References."
        )
        content = await ollama_generate(full_prompt, model_tag)
        file_path = build_inspection_report(f"SOP — {title}", content, eq_id)
        return {
            "status": "success",
            "file": file_path.name,
            "download_url": f"/outputs/{file_path.name}",
            "model_used": MODELS[model_key]["display"],
            "doc_type": "docx",
            "external_calls": 0,
        }

    elif req.doc_type == "pptx":
        full_prompt = (
            f"You are preparing a professional presentation for MRPL management.\n\n"
            f"Topic: {req.prompt}\n\n"
            f"Write 5-7 slides. Use ## for each slide title, then bullet points below.\n"
            f"Include: Title slide content, key findings, data points, recommendations, conclusion."
        )
        content = await ollama_generate(full_prompt, model_tag)
        file_path = build_pptx(title, content)
        return {
            "status": "success",
            "file": file_path.name,
            "download_url": f"/outputs/{file_path.name}",
            "model_used": MODELS[model_key]["display"],
            "doc_type": "pptx",
            "external_calls": 0,
        }

    elif req.doc_type == "xlsx":
        full_prompt = (
            f"You are creating a data spreadsheet for MRPL.\n\n"
            f"Topic: {req.prompt}\n\n"
            f"Output a table with column headers on the first line, then data rows.\n"
            f"Use | to separate columns. Include at least 5 data rows.\n"
            f"Example: Header1 | Header2 | Header3\nVal1 | Val2 | Val3"
        )
        content = await ollama_generate(full_prompt, model_tag)
        file_path = build_xlsx(title, content)
        return {
            "status": "success",
            "file": file_path.name,
            "download_url": f"/outputs/{file_path.name}",
            "model_used": MODELS[model_key]["display"],
            "doc_type": "xlsx",
            "external_calls": 0,
        }

    else:
        raise HTTPException(400, f"Unknown doc_type: {req.doc_type}")


@router.get("/list")
async def list_outputs():
    files = [
        {"name": f.name, "url": f"/outputs/{f.name}", "size_kb": round(f.stat().st_size / 1024, 1)}
        for f in sorted(OUTPUT_DIR.iterdir(), key=lambda x: x.stat().st_mtime, reverse=True)
        if f.is_file()
    ]
    return {"files": files}
